### ISSUE TITLE
 invalid IP mask "md5"

### ISSUE THREAD

**Issue by kennethgillen** [ome/ansible-role-postgresql#12]
Using version 3.0.1 of the role, with Ansible 2.4.3.0

Copying the example from Readme.txt, I tried the following:

```
  - role: openmicroscopy.postgresql
    postgresql_server_auth:
    - database: mailman3-staging
      user: mailman_db_user
      address: 127.0.0.1
    postgresql_databases:
    - name: mailman_core_db
      owner: mailman_core_db_user
      restrict: True
    - name: mailman_hyperkitty_db
      owner: mailman_hyperkitty_db_user
      restrict: True
    postgresql_users:
    - user: mailman_core_db_user
      password: **************
      databases: [mailman_core_db]
    - user: mailman_hyperkitty_db_user
      password: **************
      databases: [mailman_hyperkitty_db] 
```

The play failed trying to start PostgreSQL:

```
TASK [openmicroscopy.postgresql : postgres | start service] ************************************************************************************************
fatal: [ome-mail3-s]: FAILED! => {"changed": false, "msg": "Unable to start service postgresql-9.4: Job for postgresql-9.4.service failed because the control process exited with error code. See \"systemctl status postgresql-9.4.service\" and \"journalctl -xe\" for details.\n"}
```

Running that, it looks like the `pg_hba.conf` is not correct.

```
< 2018-08-30 14:21:45.838 UTC > LOG:  invalid IP mask "md5": Name or service not known
< 2018-08-30 14:21:45.838 UTC > CONTEXT:  line 7 of configuration file "/var/lib/pgsql/9.4/data/pg_hba.conf"
< 2018-08-30 14:21:45.838 UTC > FATAL:  could not load pg_hba.conf
```
Presumably I've picked some incompatible options?
