### ISSUE TITLE
Can't initialise database, "initdb: error: no data directory specified", v 5.1.0

### ISSUE THREAD

**Issue by marcin-github** [ome/ansible-role-postgresql#27]
Hi!
I try to use this role for Debian11 and postgresql 14. As I see in code there shouldn't be problem with using version higher than 12. But initialisation fails:

```
TASK [ome.postgresql : postgres | install ansible prerequisites] ******************************************************************************************************************************************
ok: [PZN04CMA001] => {"cache_update_time": 1652956052, "cache_updated": false, "changed": false}
Thursday 19 May 2022  16:46:07 +0200 (0:00:00.938)       0:00:10.601 **********
Thursday 19 May 2022  16:46:07 +0200 (0:00:00.939)       0:00:10.600 **********

TASK [ome.postgresql : postgres | set debian dist variables] **********************************************************************************************************************************************
ok: [xx] => {"ansible_facts": {"postgresql_dist_bindir": "/usr/lib/postgresql/14/bin", "postgresql_dist_conf_postgresql_src": "postgresql-conf-10-ubuntu.j2", "postgresql_dist_confdir": "/etc/postgresql/14/main", "postgresql_dist_datadir": "/var/lib/postgresql/14/main", "postgresql_dist_service": "postgresql", "postgresql_dist_setup": "/usr/lib/postgresql/14/bin/initdb"}, "changed": false}
Thursday 19 May 2022  16:46:07 +0200 (0:00:00.151)       0:00:10.753 **********
Thursday 19 May 2022  16:46:07 +0200 (0:00:00.151)       0:00:10.752 **********

TASK [ome.postgresql : postgres | set permissions on data directory] **************************************************************************************************************************************
skipping: [xx] => {"changed": false, "skip_reason": "Conditional result was False"}
Thursday 19 May 2022  16:46:07 +0200 (0:00:00.076)       0:00:10.829 **********
Thursday 19 May 2022  16:46:07 +0200 (0:00:00.076)       0:00:10.828 **********

TASK [ome.postgresql : postgres | initialise PostgreSQL cluster (skip if data directory already exists)] **************************************************************************************************
fatal: [xx]: FAILED! => {"changed": true, "cmd": ["/usr/lib/postgresql/14/bin/initdb"], "delta": "0:00:00.007452", "end": "2022-05-19 16:46:08.844541", "msg": "non-zero return code", "rc": 1, "start": "2022-05-19 16:46:08.837089", "stderr": "initdb: error: no data directory specified\nYou must identify the directory where the data for this database system\nwill reside.  Do this with either the invocation option -D or the\nenvironment variable PGDATA.", "stderr_lines": ["initdb: error: no data directory specified", "You must identify the directory where the data for this database system", "will reside.  Do this with either the invocation option -D or the", "environment variable PGDATA."], "stdout": "", "stdout_lines": []}
```

host variables:

```yml
postgresql_version: 14
postgresql_server_listen: "'*'"
```

**Comment by joshmoore** [comment]
Hi @marcin-github. As you can see in https://github.com/ome/ansible-role-postgresql-client/pull/5, we're just in the process of testing on the newer versions. Does setting the appropriate value of PGDATA (`export PGDATA=...`) let the role complete?

**Comment by sbesson** [comment]
Adding to https://github.com/ome/ansible-role-postgresql/issues/27#issuecomment-1132766961, I tried to reproduce this issue by extending the Molecule scenarios. Via snowball effect, this led me to addressing limitations in the upstream `ome.postgresql_client` role (https://github.com/ome/ansible-role-postgresql-client/pull/5) but I am aiming to report more on this later today or on Monday.

**Comment by sbesson** [comment]
A quick update on this issue:

- as a first incremental step, #28 adds Ubuntu 20.04 (based on Debian 11) to the supported and test platforms and add coverage for all PSQL versions up to 13
-  adding PSQL 14 to the tests results in failures across all environments - see https://github.com/sbesson/ansible-role-postgresql/runs/6526467627. Interestingly the error is the same and related to the idempotence tests rather than the initialization step

  ```
  ERROR: Idempotence test failed because of the following tasks:
  An error occurred during the test sequence action: 'idempotence'. Cleaning up.
  * [postgresql-14-c7] => (item={'user': 'alice', 'password': 'alice123', 'databases': ['publicdb'] => ansible-role-postgresql : postgres | create users
  * [postgresql-14-c7] => (item={'user': 'bob', 'password': 'bob123', 'databases': ['publicdb', 'secretdb'] => ansible-role-postgresql : postgres | create users
  * [postgresql-14-c7] => (item={'user': 'charles', 'password': 'charles123', 'databases': [] => ansible-role-postgresql : postgres | create users
   ```

It looks we are dealing with two separate issues with PostgreSQL 14 and this role. In addition to @joshmoore's question about setting `PGDATA` and to try to narrow down the issue, have you tried using either PostgreSQL 13 or Ubuntu 20.04 ?

**Comment by sysblade** [comment]
Hello.

I have the same issue on Ubuntu 20.04 + Postgresql 10.
Nothing special configured

The params are : 
```
postgresql_version: 10
postgresql_server_listen: "'*'"
postgresql_server_conf:
  max_connections: 500
  shared_buffers: 8GB
  temp_buffers: 128MB
  work_mem: 512MB
  maintenance_work_mem: 16GB
  max_worker_process: 16
  checkpoint_timeout: 1h
  max_wal_size: 10GB
```

The error:
```
TASK [postgresql : postgres | initialise PostgreSQL cluster (skip if data directory already exists)] ****************************************************************************************
fatal: [lab-piou-replika-server-1]: FAILED! => {"changed": true, "cmd": ["/usr/lib/postgresql/10/bin/initdb"], "delta": "0:00:00.007137", "end": "2022-05-23 13:40:05.387028", "msg": "non-zero return code", "rc": 1, "start": "2022-05-23 13:40:05.379891", "stderr": "initdb: no data directory specified\nYou must identify the directory where the data for this database system\nwill reside.  Do this with either the invocation option -D or the\nenvironment variable PGDATA.", "stderr_lines": ["initdb: no data directory specified", "You must identify the directory where the data for this database system", "will reside.  Do this with either the invocation option -D or the", "environment variable PGDATA."], "stdout": "", "stdout_lines": []}
```

That should be fixed when it's merged and pushed to galaxy ?

**Comment by sbesson** [comment]
@kedare a new version of the role (5.2.0) should now be available in Galaxy with the changes in #28 which are mostly cleanup of deprecated variables and additional test coverage.

You might want to give it a tryt but I don't expect this will solve your failure especially as https://github.com/ome/ansible-role-postgresql/issues/27#issuecomment-1134722516 established that Ubuntu 20.04/PSQL 10 failed for you but seems to be working with the Molecule tests of this role

The next thing I am wondering is whether there other tasks or specific conditions that would trigger this error? Could you share a minimal Ansible playbook consuming this role and allowing to reproduce the failure?

**Comment by sysblade** [comment]
The playbook is not doing much, only putting some files at specific locations, setting up mountpoints and nvme format, there is also another included role that setup users and include some cli tools (zsh, tmux, etc..)

```
---

- name: Copy custom sbin scripts
  copy:
    src: "{{item}}"
    dest: /usr/local/sbin/{{item}}
    owner: root
    group: root
    mode: 0755
  with_items: [prepare-nvme.sh, restore-db.sh]

- name: Copy custom bin scripts
  copy:
    src: "{{item}}"
    dest: /usr/local/bin/{{item}}
    owner: root
    group: root
    mode: 0755
  with_items: [restore-wal.sh]

- name: Prepare/check NVME
  command: /usr/local/sbin/prepare-nvme.sh

- name: Create mount point
  file:
    path: /mnt/nvme
    state: directory

- name: Configure fstab and mount the NVME
  mount:
    path: /mnt/nvme
    src: /dev/nvme0n1
    opts: noatime,rw
    fstype: ext4
    state: mounted

- name: Install postgresql
  include_role:
    name: postgresql

- name: Set restore.conf
  template:
    src: restore.conf.j2
    dest: /etc/postgresql/restore/restore.conf
    owner: root
    group: root
    mode: 0600

- name: Give postgres user read access to restore.conf
  acl:
    path: /etc/postgresql/restore/restore.conf
    entity: postgres
    etype: user
    permissions: r

- name: Copy recovery.conf
  copy:
    src: recovery.conf
    dest: /etc/postgresql/restore/recovery.conf
    owner: root
    group: root
    mode: 0655
```

I will try to create a blank playbook on a blank server see if it happens again.
Edit: may take more time I have to ask for quota increase to have another similar instance

**Comment by marcin-github** [comment]
> Hi @marcin-github. As you can see in [ome/ansible-role-postgresql-client#5](https://github.com/ome/ansible-role-postgresql-client/pull/5), we're just in the process of testing on the newer versions. Does setting the appropriate value of PGDATA (`export PGDATA=...`) let the role complete?

Hi,
As a workarround I set in `ome.postgresql/tasks/initialise.yml`
```
      environment:
        PGSETUP_INITDB_OPTIONS: >-
          --encoding=UTF8 --locale=en_US.UTF-8 --auth-host=md5
        PGDATA: "{{ postgresql_dist_datadir }}"

```
and I could initialise database.
