### ISSUE TITLE
Implement `privs`

### ISSUE THREAD

**Issue by joshmoore** [ome/ansible-role-postgresql#5]
See https://github.com/openmicroscopy/ansible-role-postgresql/pull/3/files#r122014822

**Comment by joshmoore** [comment]
Perhaps relatedly, users are only created if they have a database set. For this type of use case, it's useful to accept:

```
      postgresql_users_databases:
      - user: omero
        password: omero
        databases: [omero]
      - user: omeroro
        password: omeroro
        databases: []
```
